INSERT INTO escola.disciplina (nome) VALUES
    ('Português'),
    ('Matemática'),
    ('Ciências'),
    ('Estudos Sociais/Geografia'),
    ('História'),
    ('Línguas Estrangeiras'),
    ('Educação Física'),
    ('Artes'),
    ('Educação Moral e Cívica'),
    ('Tecnologia da Informação'),
    ('Literatura'),
    ('Redação/Composição'),
    ('Educação para a Saúde'),
    ('Educação Ambiental'),
    ('Educação Financeira'),
    ('Educação Sexual'),
    ('Filosofia'),
    ('Sociologia'),
    ('Psicologia'),
    ('Economia'),
    ('Química'),
    ('Física'),
    ('Biologia'),
    ('Geologia'),
    ('Astronomia'),
    ('Informática'),
    ('Programação'),
    ('Design Gráfico'),
    ('Música'),
    ('Teatro'),
    ('Dança'),
    ('Educação Religiosa'),
    ('Educação Física Adaptada'),
    ('Educação Especial'),
    ('Aulas de Reforço/Tutoria');