INSERT INTO escola.disciplina_serie (id_disciplina, id_serie) VALUES
    ((SELECT id FROM escola.disciplina WHERE nome = 'Português'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Matemática'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Ciências'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Estudos Sociais/Geografia'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'História'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Línguas Estrangeiras'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Artes'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Moral e Cívica'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Tecnologia da Informação'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Literatura'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Redação/Composição'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação para a Saúde'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Ambiental'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Financeira'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Sexual'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Filosofia'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Sociologia'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Psicologia'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Economia'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Química'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Física'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Biologia'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Geologia'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Astronomia'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Informática'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Programação'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Design Gráfico'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Música'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Teatro'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Dança'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Religiosa'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física Adaptada'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Especial'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Aulas de Reforço/Tutoria'), (SELECT id FROM escola.serie WHERE nome = 'Berçário')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Português'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Matemática'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Ciências'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Estudos Sociais/Geografia'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'História'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Línguas Estrangeiras'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Artes'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Moral e Cívica'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Tecnologia da Informação'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Literatura'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Redação/Composição'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação para a Saúde'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Ambiental'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Financeira'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Sexual'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Filosofia'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Sociologia'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Psicologia'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Economia'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Química'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Física'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Biologia'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Geologia'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Astronomia'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Informática'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Programação'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Design Gráfico'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Música'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Teatro'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Dança'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Religiosa'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física Adaptada'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Especial'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Aulas de Reforço/Tutoria'), (SELECT id FROM escola.serie WHERE nome = 'Maternal ou Creche')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Português'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Matemática'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Ciências'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Estudos Sociais/Geografia'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'História'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Línguas Estrangeiras'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Artes'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Moral e Cívica'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Tecnologia da Informação'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Literatura'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Redação/Composição'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação para a Saúde'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Ambiental'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Financeira'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Sexual'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Filosofia'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Sociologia'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Psicologia'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Economia'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Química'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Física'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Biologia'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Geologia'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Astronomia'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Informática'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Programação'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Design Gráfico'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Música'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Teatro'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Dança'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Religiosa'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física Adaptada'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Especial'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Aulas de Reforço/Tutoria'), (SELECT id FROM escola.serie WHERE nome = 'Jardim de Infância')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Português'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Matemática'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Ciências'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Estudos Sociais/Geografia'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'História'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Línguas Estrangeiras'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Artes'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Moral e Cívica'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Tecnologia da Informação'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Literatura'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Redação/Composição'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação para a Saúde'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Ambiental'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Financeira'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Sexual'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Filosofia'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Sociologia'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Psicologia'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Economia'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Química'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Física'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Biologia'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Geologia'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Astronomia'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Informática'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Programação'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Design Gráfico'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Música'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Teatro'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Dança'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Religiosa'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física Adaptada'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Especial'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Aulas de Reforço/Tutoria'), (SELECT id FROM escola.serie WHERE nome = '1º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Português'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Matemática'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Ciências'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Estudos Sociais/Geografia'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'História'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Línguas Estrangeiras'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Artes'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Moral e Cívica'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Tecnologia da Informação'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Literatura'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Redação/Composição'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação para a Saúde'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Ambiental'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Financeira'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Sexual'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Filosofia'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Sociologia'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Psicologia'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Economia'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Química'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Física'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Biologia'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Geologia'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Astronomia'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Informática'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Programação'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Design Gráfico'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Música'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Teatro'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Dança'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Religiosa'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física Adaptada'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Especial'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Aulas de Reforço/Tutoria'), (SELECT id FROM escola.serie WHERE nome = '2º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Português'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Matemática'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Ciências'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Estudos Sociais/Geografia'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'História'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Línguas Estrangeiras'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Artes'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Moral e Cívica'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Tecnologia da Informação'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Literatura'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Redação/Composição'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação para a Saúde'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Ambiental'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Financeira'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Sexual'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Filosofia'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Sociologia'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Psicologia'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Economia'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Química'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Física'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Biologia'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Geologia'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Astronomia'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Informática'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Programação'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Design Gráfico'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Música'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Teatro'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Dança'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Religiosa'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física Adaptada'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Especial'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Aulas de Reforço/Tutoria'), (SELECT id FROM escola.serie WHERE nome = '3º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Português'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Matemática'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Ciências'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Estudos Sociais/Geografia'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'História'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Línguas Estrangeiras'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Artes'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Moral e Cívica'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Tecnologia da Informação'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Literatura'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Redação/Composição'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação para a Saúde'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Ambiental'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Financeira'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Sexual'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Filosofia'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Sociologia'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Psicologia'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Economia'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Química'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Física'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Biologia'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Geologia'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Astronomia'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Informática'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Programação'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Design Gráfico'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Música'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Teatro'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Dança'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Religiosa'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física Adaptada'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Especial'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Aulas de Reforço/Tutoria'), (SELECT id FROM escola.serie WHERE nome = '4º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Português'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Matemática'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Ciências'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Estudos Sociais/Geografia'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'História'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Línguas Estrangeiras'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Artes'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Moral e Cívica'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Tecnologia da Informação'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Literatura'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Redação/Composição'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação para a Saúde'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Ambiental'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Financeira'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Sexual'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Filosofia'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Sociologia'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Psicologia'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Economia'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Química'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Física'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Biologia'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Geologia'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Astronomia'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Informática'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Programação'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Design Gráfico'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Música'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Teatro'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Dança'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Religiosa'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física Adaptada'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Especial'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Aulas de Reforço/Tutoria'), (SELECT id FROM escola.serie WHERE nome = '5º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Português'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Matemática'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Ciências'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Estudos Sociais/Geografia'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'História'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Línguas Estrangeiras'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Artes'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Moral e Cívica'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Tecnologia da Informação'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Literatura'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Redação/Composição'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação para a Saúde'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Ambiental'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Financeira'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Sexual'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Filosofia'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Sociologia'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Psicologia'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Economia'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Química'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Física'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Biologia'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Geologia'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Astronomia'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Informática'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Programação'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Design Gráfico'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Música'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Teatro'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Dança'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Religiosa'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física Adaptada'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Especial'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Aulas de Reforço/Tutoria'), (SELECT id FROM escola.serie WHERE nome = '6º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Português'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Matemática'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Ciências'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Estudos Sociais/Geografia'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'História'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Línguas Estrangeiras'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Artes'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Moral e Cívica'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Tecnologia da Informação'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Literatura'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Redação/Composição'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação para a Saúde'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Ambiental'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Financeira'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Sexual'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Filosofia'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Sociologia'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Psicologia'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Economia'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Química'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Física'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Biologia'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Geologia'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Astronomia'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Informática'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Programação'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Design Gráfico'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Música'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Teatro'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Dança'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Religiosa'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física Adaptada'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Especial'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Aulas de Reforço/Tutoria'), (SELECT id FROM escola.serie WHERE nome = '7º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Português'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Matemática'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Ciências'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Estudos Sociais/Geografia'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'História'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Línguas Estrangeiras'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Artes'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Moral e Cívica'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Tecnologia da Informação'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Literatura'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Redação/Composição'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação para a Saúde'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Ambiental'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Financeira'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Sexual'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Filosofia'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Sociologia'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Psicologia'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Economia'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Química'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Física'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Biologia'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Geologia'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Astronomia'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Informática'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Programação'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Design Gráfico'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Música'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Teatro'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Dança'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Religiosa'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física Adaptada'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Especial'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Aulas de Reforço/Tutoria'), (SELECT id FROM escola.serie WHERE nome = '8º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Português'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Matemática'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Ciências'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Estudos Sociais/Geografia'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'História'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Línguas Estrangeiras'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Artes'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Moral e Cívica'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Tecnologia da Informação'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Literatura'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Redação/Composição'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação para a Saúde'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Ambiental'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Financeira'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Sexual'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Filosofia'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Sociologia'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Psicologia'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Economia'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Química'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Física'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Biologia'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Geologia'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Astronomia'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Informática'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Programação'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Design Gráfico'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Música'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Teatro'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Dança'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Religiosa'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física Adaptada'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Especial'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Aulas de Reforço/Tutoria'), (SELECT id FROM escola.serie WHERE nome = '9º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Português'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Matemática'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Ciências'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Estudos Sociais/Geografia'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'História'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Línguas Estrangeiras'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Artes'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Moral e Cívica'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Tecnologia da Informação'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Literatura'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Redação/Composição'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação para a Saúde'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Ambiental'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Financeira'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Sexual'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Filosofia'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Sociologia'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Psicologia'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Economia'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Química'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Física'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Biologia'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Geologia'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Astronomia'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Informática'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Programação'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Design Gráfico'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Música'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Teatro'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Dança'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Religiosa'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física Adaptada'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Especial'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Aulas de Reforço/Tutoria'), (SELECT id FROM escola.serie WHERE nome = '10º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Português'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Matemática'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Ciências'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Estudos Sociais/Geografia'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'História'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Línguas Estrangeiras'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Artes'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Moral e Cívica'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Tecnologia da Informação'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Literatura'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Redação/Composição'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação para a Saúde'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Ambiental'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Financeira'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Sexual'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Filosofia'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Sociologia'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Psicologia'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Economia'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Química'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Física'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Biologia'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Geologia'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Astronomia'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Informática'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Programação'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Design Gráfico'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Música'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Teatro'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Dança'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Religiosa'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física Adaptada'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Especial'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Aulas de Reforço/Tutoria'), (SELECT id FROM escola.serie WHERE nome = '11º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Português'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Matemática'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Ciências'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Estudos Sociais/Geografia'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'História'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Línguas Estrangeiras'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Artes'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Moral e Cívica'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Tecnologia da Informação'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Literatura'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Redação/Composição'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação para a Saúde'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Ambiental'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Financeira'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Sexual'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Filosofia'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Sociologia'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Psicologia'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Economia'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Química'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Física'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Biologia'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Geologia'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Astronomia'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Informática'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Programação'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Design Gráfico'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Música'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Teatro'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Dança'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Religiosa'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Física Adaptada'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Educação Especial'), (SELECT id FROM escola.serie WHERE nome = '12º Ano')),
    ((SELECT id FROM escola.disciplina WHERE nome = 'Aulas de Reforço/Tutoria'), (SELECT id FROM escola.serie WHERE nome = '12º Ano'));