INSERT INTO escola.tipo_atividade (nome) VALUES
    ('Clube de Ciências'),
    ('Clube de Música'),
    ('Clube de Arte'),
    ('Clube de Teatro'),
    ('Clube de Dança'),
    ('Esporte - Futebol'),
    ('Esporte - Basquete'),
    ('Esporte - Vôlei'),
    ('Esporte - Natação'),
    ('Evento - Feira de Ciências'),
    ('Evento - Festival Cultural'),
    ('Evento - Apresentação de Talentos'),
    ('Evento - Dia Temático'),
    ('Projeto de Pesquisa'),
    ('Aula de Educação Física'),
    ('Atividade Voluntária'),
    ('Palestra ou Workshop'),
    ('Excursão ou Viagem de Estudo'),
    ('Discussão em Sala de Aula'),
    ('Desenvolvimento Profissional');
