CREATE TABLE IF NOT EXISTS escola.aluno (
    id BINARY(16) DEFAULT (UUID_TO_BIN(UUID(), 1)) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    idade INTEGER NOT NULL CHECK (idade BETWEEN 3 AND 17),
    email VARCHAR(100) CHECK (email = '' OR email LIKE '%@%'),
    sexo VARCHAR(10) NOT NULL CHECK (sexo IN ('M', 'F')),
    data_insercao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_alteracao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);